### ISSUE TITLE
Luarocks fails to install dependencies

### ISSUE THREAD

**Issue by beauwilliams** [WhoIsSethDaniel/mason-tool-installer.nvim#14]
This is not the plugin, it will fail on CLI for me too. Perhaps we need a flag here to auto install deps and not fail..

`luarocks install --tree /Users/admin/.local/share/nvim/mason/packages/luacheck luacheck` --> fails, argparse is not installed

`luarocks install --tree /Users/admin/.local/share/nvim/mason/packages/luacheck argparse && luarocks install --tree /Users/admin/.local/share/nvim/mason/packages/luacheck luacheck` --> does not fail, installing argparse manually

**Comment by WhoIsSethDaniel** [comment]
Have you submitted this upstream to `mason`? The seems more like a `mason` issue than an issue for `mason-tool-installer` unless I misunderstand.

**Comment by beauwilliams** [comment]
I've submitted upstream issue https://github.com/williamboman/mason.nvim/issues/432

**Comment by WhoIsSethDaniel** [comment]
Seems to be an upstream problem. Probably a luarocks issue.
