### ISSUE TITLE
golangci-lint: failed to install

### ISSUE THREAD

**Issue by beauwilliams** [WhoIsSethDaniel/mason-tool-installer.nvim#15]
This is because it is saying the version is invalid.

`go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@1.49.0` --> is the command being run

`go: github.com/golangci/golangci-lint/cmd/golangci-lint@1.49.0: github.com/golangci/golangci-lint/cmd/golangci-lint@1.49.0: invalid version: unknown revision 1.49.0
zsh: exit 1     go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@1.49.0` --> is the output of failure

We can use @latest instead of @1.49.0 instead. Mason installs fine (uses @latest) but for some reason issue with this plugin.

Edit: Oh its from the readme. Missed that.

`    -- { 'golangci-lint', version = '1.47.0' },` <-- will fail
`    -- { 'golangci-lint', version = 'v1.47.0' },` <-- will work

**Comment by WhoIsSethDaniel** [comment]
Responded in the PR #16.
