### ISSUE TITLE
Debounce for auto-update

### ISSUE THREAD

**Issue by xbc5** [WhoIsSethDaniel/mason-tool-installer.nvim#20]
Rather than auto-update occurring on every startup, have an option that sets the debounce time in hour:

```
debounce_update = 24,
```

**Comment by WhoIsSethDaniel** [comment]
I like the idea but AFAIK requires storing state. I'm not certain I want to do that for this plugin.

**Comment by xbc5** [comment]
A simple "last_updated" under ~/.local/cache/... would suffice. Right now the auto update feature is unusable because it will hit the Github servers every time I restart, and slow down my instance for about 20 seconds.

Perhaps I should just create a headless update script instead. It's probably a better approach.

**Comment by WhoIsSethDaniel** [comment]
I think it's probably a good idea to have this feature so I'll likely work on it soon.

I'm interested in the "unusable" and "slow down" comments, though. I don't see either of these with my daily use of this plugin. If it weren't for the output from the plugin I wouldn't be able to tell that something was being updated. It all happens in the background. Any idea why your experience would be so different?

**Comment by serhez** [comment]
Hello! I love this plugin and really want to continue using it, but I agree with @xbc5 that, due to `mason-tool-installer` not using concurrent jobs/threads to make the checks and updates, I see a great deal of lag every time I run Neovim (in my case, it happens after 5 seconds, as that's my configured delay). This for me is the greatest improvement you could do to this plugin: making the checks and updates async without affecting the editor's performance. Thanks for your work on this! 😄

**Comment by xbc5** [comment]
> Any idea why your experience would be so different?

Possibly because I run nvim inside of a virtual machine, on a laptop. Then again it's nvim that locks up, not my VM or machine. However, I simply just disable auto-update and run it manually. It's done pretty quickly, so there's no real inconvenience.

**Comment by WhoIsSethDaniel** [comment]
Sorry it has been so long since responding. I like this idea. I will work on allowing de-bouncing. Likely with hour granularity. So you can configure with something like "only check once every 12 hours" (or 24 hours or 48 hours etc....).

**Comment by serhez** [comment]
Would it still be possible to run the update job async? @WhoIsSethDaniel

**Comment by xbc5** [comment]
@WhoIsSethDaniel Yes it works. Sorry it's late.

**Comment by xbc5** [comment]
> Would it still be possible to run the update job async? @WhoIsSethDaniel

Raise a new issue.
