### ISSUE TITLE
Trigger :Mason

### ISSUE THREAD

**Issue by tnxz** [WhoIsSethDaniel/mason-tool-installer.nvim#21]
Is there anyway to trigger ```:Mason``` when tools are being installed( to get a view of the installation)?

**Comment by WhoIsSethDaniel** [comment]
No. That seems potentially disrupting. However, I may be able to add an event that is triggered at the start of installation. You would be able to do whatever you want to do with that event, including trigger `:Mason`. 

Would that work for you?

**Comment by tnxz** [comment]
That would be great.

**Comment by WhoIsSethDaniel** [comment]
I have implemented an event that is emitted just prior to any packages being installed. It is documented here: https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim#events. If you have any questions let me know. If it works for you please close this ticket. Thank you.

**Comment by tnxz** [comment]
yes, that worked great
```
      vim.api.nvim_create_autocmd("User", {
        pattern = "MasonToolsStartingInstall",
        command = "Mason",
      })
``` 
thank you
