### ISSUE TITLE
[Bug] Python LSP Pyre

### ISSUE THREAD

**Issue by ALipAkrohk** [WhoIsSethDaniel/mason-tool-installer.nvim#23]
I feel there is a problem, which needs to be investigated.
Unfortunately, there are some language servers that are not shown in the installation suggestions.

https://github.com/williamboman/mason.nvim/issues/456#issuecomment-1399521730
https://github.com/williamboman/mason-lspconfig.nvim/issues/46

**Comment by WhoIsSethDaniel** [comment]
I don't think this has anything to do with this plugin. It looks like you have, or someone, has already filed a ticket for mason -- which is likely the correct plugin. So I will close this ticket.
