### ISSUE TITLE
callback args for MasonToolsUpdateCompleted

### ISSUE THREAD

**Issue by chuan137** [WhoIsSethDaniel/mason-tool-installer.nvim#29]
any chance to add the newly installed lsp to the callback args of the event  MasonToolsUpdateCompleted? or is it already possible?

I would like to call lsp config for the newly installed servers in the callback, but not the others. Sometimes, after configuring lsp server, the diagnostic info are not showing correctly. I have to restart vim or do a "LspRestart" to get everything right again in the open buffer.

**Comment by WhoIsSethDaniel** [comment]
I don't *think* adding this will be difficult. I'll look at it soon.

**Comment by WhoIsSethDaniel** [comment]
Sorry, real-life intruded and I'm only now able to look at this.

**Comment by WhoIsSethDaniel** [comment]
I have just implemented this. Let me know if it is enough. I have also updated the docs, but here is a summary:

Create an autocomand, e.g.:
```
vim.api.nvim_create_autocmd('User', {
    pattern = { 'MasonToolsUpdateCompleted' },
       callback = function(e)
           print(vim.inspect(e.data))
       end,
  })
```

If this plugin runs and installs two things, those two things will be in a table in e.data. e.g. if `gopls` and `lua-language-server` are installed then the above autocmd will print `{ 'gopls', 'lua-language-server'}`.

**Comment by WhoIsSethDaniel** [comment]
I'll close this ticket when I've merged the code.

**Comment by WhoIsSethDaniel** [comment]
It was passing the name of the server that was installed. Instead I've just changed it to have the Package object for each program that is installed. You can get the name with `p.name`. The documentation for the package object is [here](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md#package)

**Comment by WhoIsSethDaniel** [comment]
n/m the packages are too big, it seems. I've gone back to just passing the names.
