### ISSUE TITLE
What's the relationship between this plugin with williamboman/mason-lspconfig.nvim?

### ISSUE THREAD

**Issue by tristone13th** [WhoIsSethDaniel/mason-tool-installer.nvim#3]
FYI:
[williamboman/mason-lspconfig.nvim: Extension to mason.nvim that makes it easier to use lspconfig with mason.nvim](https://github.com/williamboman/mason-lspconfig.nvim)

**Comment by WhoIsSethDaniel** [comment]
`mason-tool-installer` uses Mason's public API to do something that, currently, Mason does not do.

**Comment by tristone13th** [comment]
> `mason-tool-installer` uses Mason's public API to do something that, currently, Mason does not do.

But it seems mason-lspconfig.nvim can also do some auto installation work.

**Comment by WhoIsSethDaniel** [comment]
`mason-lspconfig` can do *some* installation, that is true. You can use both. You can use one, the other, or neither. It depends on your needs.  I don't use `mason-lspconfig` for installation since I need to install a lot more than LSP servers. I use `mason-lspconfig` for `setup_handlers()` and I use `mason-tool-installer` for all my installation.

**Comment by tristone13th** [comment]
OK, thanks!

**Comment by ndom91** [comment]
@tristone13th I found a great example config doing what @WhoIsSethDaniel is doing here: https://github.com/alpha2phi/neovim-for-beginner/blob/main/lua/config/lsp/installer.lua

**Comment by WhoIsSethDaniel** [comment]
You can use both. That is a correct statement. I don't happen to use both, but you can do it. "Using both" has nothing at all to do with ordering of plugins, or lazy loading, or what plugin installer you happen to use. These are orthogonal tasks.

As for the server names the README for `mason-tool-installer` does say that the name of the thing to be installed should be the name `mason` uses for that thing. i.e. use `lua-language-server`, not `lua_ls`.  It is interesting that `mason` seems to work with all of these names now as I don't believe it always has. I will make an issue to look into that. I'd be fine if `mason-tool-installer` worked with all possible names. For now it doesn't.

I believe there may be a misunderstanding. `mason-tool-installer` has nothing to do with `mason-lspconfig`. This plugin is its own thing. `mason-lspconfig` is not a dependency. It's designed to automatically install *anything* that `mason` can install regardless of whether it's an LSP server or something else.

**Comment by WhoIsSethDaniel** [comment]
Why would you list the server you need in both `mason-lspconfig` and `mason-tool-installer`? That makes no sense. Don't do that.
