### ISSUE TITLE
FR: cleanup on startup

### ISSUE THREAD

**Issue by chrisgrieser** [WhoIsSethDaniel/mason-tool-installer.nvim#33]
Plugin managers like `lazy.nvim` are also able to automatically uninstall unused plugins. This is particularly useful when working on multiple machines, and you want to keep your installed tools in sync as well.

Currently, `ensure_installed` only ensures that a tool that is listed, but not installed, is being automatically installed. However, tools that are installed but not listed are not automatically uninstalled.

**Comment by WhoIsSethDaniel** [comment]
Anything that does this would need to be opt-in. I often install things using the `:Mason` menu. Eventually I may add it to my list of things to automatically install, or I may delete it. 

This seems like a reasonable request. I can see it as a user command or api call. This can be called by the user whenever the user wants it to run including startup.

**Comment by WhoIsSethDaniel** [comment]
The current `main` has a new command: `MasonToolsClean`. Try it out. Let me know if it works for you. Currently no documentation.

**Comment by chrisgrieser** [comment]
Thank you very much! I just gave it a try and so far everything seems to work.

Only thing I noticed was that as opposed to `MasonToolsInstall`, there are apparently no notifications to inform you about the cleanup (yet).

**Comment by WhoIsSethDaniel** [comment]
It's using `vim.notify` to print the messages.
