### ISSUE TITLE
configuration comments in README unclear

### ISSUE THREAD

**Issue by oalders** [WhoIsSethDaniel/mason-tool-installer.nvim#51]
I got this working yesterday and it's great!

```lua
  -- Disable integration with other Mason plugins. This removes
  -- the ability to to use the alternative names of packages provided
  -- by these plugins but disables them from immediately becoming loaded
    integrations = {
        ['mason-lspconfig'] = true,
        ['mason-null-ls'] = true,
        ['mason-nvim-dap'] = true,
    },
```

It's not clear to me what this is saying. If the integrations are being disabled, I would expect the example to have them set to `false`. Also the wording of "This removes ... but disables" could be clearer.

**Comment by WhoIsSethDaniel** [comment]
The text can be better. `true` means it is enabled. `false` means disabled. I didn't write this bit of code so I had to look at the code to remember what it is doing. IIRC the reasoning for it is, for at least some people while lazy loading, having to load  `nvim-lspconfig`, `mason-null-ls`, or `mason-nvim-dap` so early was more than they wanted. They aren't hard dependencies, but if you have them installed you may not want them to load as early as `mason-tool-installer` requires them. Each of these 'integrations' is `true` by default which is what that block shows, the defaults.

I'll update the text in a forthcoming PR.
